name: Pipeline

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Specify the Python version you need

      - name: Install requirements
        run: pip install --quiet --requirement requirements.txt

      - name: Lint code
        run: |
          # Run flake8 with custom configuration
          flake8 --config .flake8 --ignore=E501,E231 *.py

          # Run pylint with custom configuration
          pylint --rcfile .pylintrc --disable=C0301,C0326 *.py

      - name: Run unit tests
        run: |
          python -m unittest --verbose --failfast

  build_image:
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '274.0.1'
          service_account_email: ${{ secrets.GCP_SERVICE_ACCT_EMAIL }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCT_KEY }}

      - name: Configure GCloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region ${{ secrets.GCP_REGION }}
          gcloud auth configure-docker
          gcloud info

      - name: Build and tag image
        run: |
          docker build -t "gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APPLICATION_NAME }}:latest" .

      - name: Push to GCP image registry
        run: |
          docker push "gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APPLICATION_NAME }}:latest"
