name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install --quiet --requirement requirements.txt

      - name: Lint with flake8
        run: flake8 --ignore=E501,E231 *.py

      - name: Lint with pylint
        run: pylint --disable=C0301 --disable=C0326 *.py

      - name: Run unit tests
        run: python -m unittest --verbose --failfast

      - name: Set up GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@latest
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SERVICE_ACCT_EMAIL }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCT_KEY }}

      - run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region ${{ secrets.GCP_REGION }}
          gcloud auth configure-docker
          gcloud info

      - name: Build and tag Docker image
        run: docker build -t "gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APPLICATION_NAME }}:${{ github.run_number }}" .

      - name: Push Docker image to GCP registry
        run: docker push "gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APPLICATION_NAME }}:${{ github.run_number }}"

